# Generated by Django 5.2.5 on 2025-08-10 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('group', models.CharField(blank=True, choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Work', 'Work'), ('Clients', 'Clients'), ('Others', 'Others')], default='Others', max_length=20)),
                ('favourite', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Home', 'Home'), ('Work', 'Work'), ('WhatsApp', 'Whatsapp'), ('Other', 'Other')], default='Mobile', max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contacts.contact')),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name', 'email', 'group', 'favourite'], name='contacts_co_name_d741b1_idx'),
        ),
    ]
