# Generated by Django 5.2.5 on 2025-08-11 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrauthsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='qrauthsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
